<?php

namespace Tests\Feature;

use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class UserTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        // Acting User
        $user = User::first();
        $this->actingAs($user);
    }

    /**
     * A basic feature test example.
     */
    public function test_example_http_success(): void
    {
        $response = $this->get(route("welcome"));
        $response->assertStatus(200);
    }

    public function test_example_http_failed(): void {
        $response = $this->post(route("welcome"));
        $response->assertStatus(405);
    }

    public function test_user_view_success(): void {
        $response = $this->get(route("client.users"));
        $response->assertViewIs("user.index");
    }

    public function test_user_url_not_found(): void {
        $response = $this->get('/userss');
        $response->assertStatus(404);
    }
}
